### ISSUE TITLE
Please add a github Release

### ISSUE THREAD

**Issue by pausanro-ei** [andre487/gulp-cleaner-css#6]
HHello,

In order to use the gulp-cleaner-css package in a standardized way, would it be possible to **create an official Release** of sources under github?

Thank you very much for your help.

**Comment by andre487** [comment]
Hello!

Can you provide more information about needed type of release?

**Comment by pausanro-ei** [comment]
Hello Andre,

Thank you for your return.

In my company, we only accept the use of official releases, in order to be able to monitor updates, for example bugs, developments, security issues etc.

So I will need release **4.3.1**

Something like here: https://github.com/scniro/gulp-clean-css/releases

Thank you in advance for your help

**Comment by pausanro-ei** [comment]
Hello Andrey,

I would like to follow up with you on this request

Regards

**Comment by andre487** [comment]
OK, I'll do it. I'll try to do it as soon as possible.

**Comment by pausanro-ei** [comment]
Thank you very much.

**Comment by andre487** [comment]
New release is ready: https://github.com/andre487/gulp-cleaner-css/releases/tag/v4.3.2

**Comment by pausanro-ei** [comment]
Thank you for your action.
